find_package(PkgConfig REQUIRED)

if(PKGCONFIG_FOUND)
  if(TRUE)#${CMAKE_VERSION} VERSION_LESS "3.1.0")
    message(STATUS "Using PKG_CONFIG_PATH in the environment for pkgconfig")
    set(ENV{PKG_CONFIG_PATH} "${PETSC_DIR}/${PETSC_ARCH}/lib/pkgconfig/")
    #    set(ENV{PKG_CONFIG_PATH} "${CMAKE_BINARY_DIR}/")
  else()
    message(STATUS "Using CMAKE_PREFIX_PATH for pkgconfig")
    list(APPEND CMAKE_PREFIX_PATH "${PETSC_DIR}/${PETSC_ARCH}/lib/pkgconfig/")
    set(PKG_CONFIG_USE_CMAKE_PREFIX_PATH true)
  endif()

  if(PETSC_FIND_REQUIRED)
    set(_PETSC_OPTS "REQUIRED")
  endif()
  if(PETSC_FIND_QUIETLY)
    set(_PETSC_OPTS "QUIET")
  endif()
  if(PETSC_FIND_REQUIRED AND PETSC_FIND_QUIETLY)
    set(_PETSC_OPTS "REQUIRED QUIET")
  endif()

  pkg_check_modules(PETSC ${_PETSC_OPTS} PETSc REQUIRED)

endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PETSC DEFAULT_MSG PETSC_LIBRARIES PETSC_INCLUDE_DIRS)
mark_as_advanced(PETSC_LIBRARIES PETSC_INCLUDE_DIRS)
